// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID            int    `json:"id"`
	Email         string `json:"email"`
	Label         string `json:"label"`
	OriginalLabel string `json:"original_label"`
}
